## EGA SULFIKA_2009106011

## Import Library

In [45]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

## Melihat Dataset

In [46]:
df = pd.read_csv("music_genre.csv")

df.head()

,instance_id,artist_name,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,obtained_date,valence,music_genre
0,32894.0,Röyksopp,Röyksopp's Night Out,27.0,0.00468,0.652,-1.0,0.941,0.79200,A#,0.115,-5.201,Minor,0.0748,100.889,4-Apr,0.759,Electronic
1,46652.0,Thievery Corporation,The Shining Path,31.0,0.01270,0.622,218293.0,0.890,0.95000,D,0.124,-7.043,Minor,0.0300,115.00200000000001,4-Apr,0.531,Electronic
2,30097.0,Dillon Francis,Hurricane,28.0,0.00306,0.620,215613.0,0.755,0.01180,G#,0.534,-4.617,Major,0.0345,127.994,4-Apr,0.333,Electronic
3,62177.0,Dubloadz,Nitro,34.0,0.02540,0.774,166875.0,0.700,0.00253,C#,0.157,-4.498,Major,0.2390,128.014,4-Apr,0.270,Electronic
4,24907.0,What So Not,Divide & Conquer,32.0,0.00465,0.638,222369.0,0.587,0.90900,F#,0.157,-6.266,Major,0.0413,145.036,4-Apr,0.323,Electronic

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50005 entries, 0 to 50004
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   instance_id       50000 non-null  float64
 1   artist_name       50000 non-null  object
 2   track_name        50000 non-null  object
 3   popularity        50000 non-null  float64
 4   acousticness      50000 non-null  float64
 5   danceability      50000 non-null  float64
 6   duration_ms       50000 non-null  float64
 7   energy            50000 non-null  float64
 8   instrumentalness  50000 non-null  float64
 9   key               50000 non-null  object
 10  liveness          50000 non-null  float64
 11  loudness          50000 non-null  float64
 12  mode              50000 non-null  object
 13  speechiness       50000 non-null  float64
 14  tempo             50000 non-null  object
 15  obtained_date     50000 non-null  object
 16  valence           50000 non-null  float64
 17  music_genre       50000 non-null  object
dtypes: float64(11), object(7)
memory usage: 6.9+ MB

In [48]:
df.shape

(50005, 18)

## Bagi dataset menjadi training set dan testing set dengan proporsi 70:30 / DATA SPLIT

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1] 

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [51]:
print("Dimensi X_train : ", x_train.shape)
print("Dimensi X_train : ", x_test.shape)
print("Dimensi y_train : ", y_train.shape)
print("Dimensi y_test  : ", y_test.shape)

Dimensi X_train :  (35003, 17)
Dimensi X_train :  (15002, 17)
Dimensi y_train :  (35003,)
Dimensi y_test  :  (15002,)

## Lakukan Data cleaning pada data dengan nilai null

In [52]:
#mengecek data dengan nilai null 
df.isna().sum()

instance_id         5
artist_name         5
track_name          5
popularity          5
acousticness        5
danceability        5
duration_ms         5
energy              5
instrumentalness    5
key                 5
liveness            5
loudness            5
mode                5
speechiness         5
tempo               5
obtained_date       5
valence             5
music_genre         5
dtype: int64

In [53]:
#mengecek type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50005 entries, 0 to 50004
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   instance_id       50000 non-null  float64
 1   artist_name       50000 non-null  object
 2   track_name        50000 non-null  object
 3   popularity        50000 non-null  float64
 4   acousticness      50000 non-null  float64
 5   danceability      50000 non-null  float64
 6   duration_ms       50000 non-null  float64
 7   energy            50000 non-null  float64
 8   instrumentalness  50000 non-null  float64
 9   key               50000 non-null  object
 10  liveness          50000 non-null  float64
 11  loudness          50000 non-null  float64
 12  mode              50000 non-null  object
 13  speechiness       50000 non-null  float64
 14  tempo             50000 non-null  object
 15  obtained_date     50000 non-null  object
 16  valence           50000 non-null  float64
 17  music_genre       50000 non-null  object
dtypes: float64(11), object(7)
memory usage: 6.9+ MB

In [54]:
df.select_dtypes(include=['object']).head(5)

,artist_name,track_name,key,mode,tempo,obtained_date,music_genre
0,Röyksopp,Röyksopp's Night Out,A#,Minor,100.889,4-Apr,Electronic
1,Thievery Corporation,The Shining Path,D,Minor,115.00200000000001,4-Apr,Electronic
2,Dillon Francis,Hurricane,G#,Major,127.994,4-Apr,Electronic
3,Dubloadz,Nitro,C#,Major,128.014,4-Apr,Electronic
4,What So Not,Divide & Conquer,F#,Major,145.036,4-Apr,Electronic

In [55]:
#(tulisan : modus)
from sklearn.impute import SimpleImputer
imputerString = SimpleImputer(strategy="most_frequent")

In [56]:
df["artist_name"] = imputerString.fit_transform(df[["artist_name"]])
df["track_name"] = imputerString.fit_transform(df[["track_name"]])
df["key"] = imputerString.fit_transform(df[["key"]])
df["mode"] = imputerString.fit_transform(df[["mode"]])
df["tempo"] = imputerString.fit_transform(df[["tempo"]])
df["obtained_date"] = imputerString.fit_transform(df[["obtained_date"]])
df["music_genre"] = imputerString.fit_transform(df[["music_genre"]])

In [57]:
df.isna().sum()

instance_id         5
artist_name         0
track_name          0
popularity          5
acousticness        5
danceability        5
duration_ms         5
energy              5
instrumentalness    5
key                 0
liveness            5
loudness            5
mode                0
speechiness         5
tempo               0
obtained_date       0
valence             5
music_genre         0
dtype: int64

In [58]:
#mengecek atribut bertipe desimal
df.select_dtypes(include=['float64']).head(5)

,instance_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,valence
0,32894.0,27.0,0.00468,0.652,-1.0,0.941,0.79200,0.115,-5.201,0.0748,0.759
1,46652.0,31.0,0.01270,0.622,218293.0,0.890,0.95000,0.124,-7.043,0.0300,0.531
2,30097.0,28.0,0.00306,0.620,215613.0,0.755,0.01180,0.534,-4.617,0.0345,0.333
3,62177.0,34.0,0.02540,0.774,166875.0,0.700,0.00253,0.157,-4.498,0.2390,0.270
4,24907.0,32.0,0.00465,0.638,222369.0,0.587,0.90900,0.157,-6.266,0.0413,0.323

In [59]:
#(bilangan desimal : mean)
imputerFloat = SimpleImputer(strategy="mean")

In [60]:
df['instance_id'] = imputerFloat.fit_transform(df[["instance_id"]])
df['acousticness'] = imputerFloat.fit_transform(df[["acousticness"]])
df['danceability'] = imputerFloat.fit_transform(df[["danceability"]])
df['duration_ms'] = imputerFloat.fit_transform(df[["duration_ms"]])
df['energy'] = imputerFloat.fit_transform(df[["energy"]])
df['instrumentalness'] = imputerFloat.fit_transform(df[["instrumentalness"]])
df['liveness'] = imputerFloat.fit_transform(df[["liveness"]])
df['loudness'] = imputerFloat.fit_transform(df[["loudness"]])
df['speechiness'] = imputerFloat.fit_transform(df[["speechiness"]])
df['valence'] = imputerFloat.fit_transform(df[["valence"]])

In [61]:
df.isna().sum()

instance_id         0
artist_name         0
track_name          0
popularity          5
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
speechiness         0
tempo               0
obtained_date       0
valence             0
music_genre         0
dtype: int64

In [62]:
#(bilangan bulat : median)
imputerBulat = SimpleImputer(strategy='median' )

In [63]:
df["popularity"] = imputerBulat.fit_transform(df[["popularity"]])

df.isna().sum()

instance_id         0
artist_name         0
track_name          0
popularity          0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
speechiness         0
tempo               0
obtained_date       0
valence             0
music_genre         0
dtype: int64

## Lakukan Data cleaning pada data dengan nilai duplikat

In [64]:
df.shape

(50005, 18)

In [65]:
df.tail()

,instance_id,artist_name,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,obtained_date,valence,music_genre
50000,58878.0,BEXEY,GO GETTA,59.0,0.03340,0.913,-1.0,0.574,0.0,C#,0.119,-7.022,Major,0.2980,98.02799999999999,4-Apr,0.330,Hip-Hop
50001,43557.0,Roy Woods,Drama (feat. Drake),72.0,0.15700,0.709,251860.0,0.362,0.0,B,0.109,-9.814,Major,0.0550,122.04299999999999,4-Apr,0.113,Hip-Hop
50002,39767.0,Berner,Lovin' Me (feat. Smiggz),51.0,0.00597,0.693,189483.0,0.763,0.0,D,0.143,-5.443,Major,0.1460,131.079,4-Apr,0.395,Hip-Hop
50003,57944.0,The-Dream,Shawty Is Da Shit,65.0,0.08310,0.782,262773.0,0.472,0.0,G,0.106,-5.016,Minor,0.0441,75.88600000000001,4-Apr,0.354,Hip-Hop
50004,63470.0,Naughty By Nature,Hip Hop Hooray,67.0,0.10200,0.862,267267.0,0.642,0.0,F#,0.272,-13.652,Minor,0.1010,99.20100000000001,4-Apr,0.765,Hip-Hop

In [66]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
50000    False
50001    False
50002    False
50003    False
50004    False
Length: 50005, dtype: bool

In [67]:
df.duplicated().sum()

4

In [68]:
df[df.duplicated()]

,instance_id,artist_name,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,obtained_date,valence,music_genre
10001,55888.39636,empty_field,Home,45.0,0.306383,0.558241,221252.60286,0.599755,0.181601,G,0.193896,-9.133761,Major,0.093586,?,4-Apr,0.456264,Alternative
10002,55888.39636,empty_field,Home,45.0,0.306383,0.558241,221252.60286,0.599755,0.181601,G,0.193896,-9.133761,Major,0.093586,?,4-Apr,0.456264,Alternative
10003,55888.39636,empty_field,Home,45.0,0.306383,0.558241,221252.60286,0.599755,0.181601,G,0.193896,-9.133761,Major,0.093586,?,4-Apr,0.456264,Alternative
10004,55888.39636,empty_field,Home,45.0,0.306383,0.558241,221252.60286,0.599755,0.181601,G,0.193896,-9.133761,Major,0.093586,?,4-Apr,0.456264,Alternative

In [69]:
#Menangani nilai duplikat
df.drop_duplicates(inplace=True)

In [70]:
#Menampilkan nilai duplikat setelah di hapus
df.duplicated().sum()

0

## Ganti tipe data salah satu attribute angka

In [71]:
df.dtypes

instance_id         float64
artist_name          object
track_name           object
popularity          float64
acousticness        float64
danceability        float64
duration_ms         float64
energy              float64
instrumentalness    float64
key                  object
liveness            float64
loudness            float64
mode                 object
speechiness         float64
tempo                object
obtained_date        object
valence             float64
music_genre          object
dtype: object

In [72]:
df["instance_id"] = df["instance_id"].astype("int64")
print(df["instance_id"].dtypes)

int64

In [73]:
df.dtypes

instance_id           int64
artist_name          object
track_name           object
popularity          float64
acousticness        float64
danceability        float64
duration_ms         float64
energy              float64
instrumentalness    float64
key                  object
liveness            float64
loudness            float64
mode                 object
speechiness         float64
tempo                object
obtained_date        object
valence             float64
music_genre          object
dtype: object

## Lakukan normalisasi data pada salah satu attribute menggunakan Min Max scaler (buatlah copy dataset terlebih dahulu)

In [74]:
from sklearn.preprocessing import MinMaxScaler

In [75]:
minMaxScaler = MinMaxScaler()

In [76]:
x_scaled = minMaxScaler.fit_transform(df[['instance_id', 'popularity','acousticness','danceability','duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness', 'valence']])

In [77]:
dataNormalization = pd.DataFrame(x_scaled)

In [78]:
dataNormalization.head()

,0,1,2,3,4,5,6,7,8,9,10
0,0.179662,0.272727,0.004699,0.639465,0.000000,0.941896,0.795181,0.106358,0.823883,0.057084,0.765121
1,0.371392,0.313131,0.012751,0.607081,0.045190,0.890804,0.953815,0.115446,0.787616,0.008372,0.535282
2,0.140683,0.282828,0.003072,0.604922,0.044635,0.755562,0.011847,0.529450,0.835381,0.013265,0.335685
3,0.587748,0.343434,0.025502,0.771157,0.034546,0.700463,0.002540,0.148769,0.837724,0.235620,0.272177
4,0.068356,0.323232,0.004669,0.624352,0.046034,0.587260,0.912651,0.148769,0.802914,0.020659,0.325605

## Lakukan standarisasi pada dataset (buatlah copy dataset terlebih dahulu)

In [79]:
# menampilkan Nilai sebelum standarisasi
np.std(df)

C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\fromnumeric.py:3571: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

instance_id          20724.841752
popularity              15.541698
acousticness             0.341333
danceability             0.178628
duration_ms         128669.383744
energy                   0.264554
instrumentalness         0.325403
liveness                 0.161634
loudness                 6.162866
speechiness              0.101371
valence                  0.247114
dtype: float64

In [80]:
from sklearn.preprocessing import StandardScaler

In [81]:
standardScaler = StandardScaler()

In [82]:
x_skala = standardScaler.fit_transform(df[['instance_id', 'popularity','acousticness','danceability','duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness', 'valence']])

In [83]:
# menampilkan Nilai setelah standarisasi
np.std(x_skala)

0.9999999999999998

In [84]:
dataStandarisasi = pd.DataFrame(x_skala)

In [85]:
dataStandarisasi.head()

,0,1,2,3,4,5,6,7,8,9,10
0,-1.109509,-1.108015,-0.883895,0.524883,-1.719551,1.289889,1.875828,-0.488118,0.638138,-0.185324,1.225085
1,-0.445668,-0.850643,-0.860399,0.356937,-0.023002,1.097112,2.361381,-0.432437,0.339251,-0.627264,0.302434
2,-1.244468,-1.043672,-0.888641,0.345740,-0.043830,0.586819,-0.521817,2.104161,0.732899,-0.582873,-0.498817
3,0.303433,-0.657614,-0.823192,1.207866,-0.422615,0.378922,-0.550305,-0.228272,0.752209,1.434467,-0.753760
4,-1.494892,-0.786300,-0.883983,0.446508,0.008676,-0.048212,2.235383,-0.228272,0.465329,-0.515792,-0.539284

## Lakukan one hot encoding pada dataset yang kalian miliki.

In [86]:
from sklearn.preprocessing import OneHotEncoder

In [87]:
df.head()

,instance_id,artist_name,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,obtained_date,valence,music_genre
0,32894,Röyksopp,Röyksopp's Night Out,27.0,0.00468,0.652,-1.0,0.941,0.79200,A#,0.115,-5.201,Minor,0.0748,100.889,4-Apr,0.759,Electronic
1,46652,Thievery Corporation,The Shining Path,31.0,0.01270,0.622,218293.0,0.890,0.95000,D,0.124,-7.043,Minor,0.0300,115.00200000000001,4-Apr,0.531,Electronic
2,30097,Dillon Francis,Hurricane,28.0,0.00306,0.620,215613.0,0.755,0.01180,G#,0.534,-4.617,Major,0.0345,127.994,4-Apr,0.333,Electronic
3,62177,Dubloadz,Nitro,34.0,0.02540,0.774,166875.0,0.700,0.00253,C#,0.157,-4.498,Major,0.2390,128.014,4-Apr,0.270,Electronic
4,24907,What So Not,Divide & Conquer,32.0,0.00465,0.638,222369.0,0.587,0.90900,F#,0.157,-6.266,Major,0.0413,145.036,4-Apr,0.323,Electronic

In [89]:
encoder = OneHotEncoder(sparse=False)
mode = encoder.fit_transform(df[["mode"]])

modes = pd.DataFrame(mode)
df = df.join(modes)
df.head()

,instance_id,artist_name,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,obtained_date,valence,music_genre,0,1
0,32894,Röyksopp,Röyksopp's Night Out,27.0,0.00468,0.652,-1.0,0.941,0.79200,A#,0.115,-5.201,Minor,0.0748,100.889,4-Apr,0.759,Electronic,0.0,1.0
1,46652,Thievery Corporation,The Shining Path,31.0,0.01270,0.622,218293.0,0.890,0.95000,D,0.124,-7.043,Minor,0.0300,115.00200000000001,4-Apr,0.531,Electronic,0.0,1.0
2,30097,Dillon Francis,Hurricane,28.0,0.00306,0.620,215613.0,0.755,0.01180,G#,0.534,-4.617,Major,0.0345,127.994,4-Apr,0.333,Electronic,1.0,0.0
3,62177,Dubloadz,Nitro,34.0,0.02540,0.774,166875.0,0.700,0.00253,C#,0.157,-4.498,Major,0.2390,128.014,4-Apr,0.270,Electronic,1.0,0.0
4,24907,What So Not,Divide & Conquer,32.0,0.00465,0.638,222369.0,0.587,0.90900,F#,0.157,-6.266,Major,0.0413,145.036,4-Apr,0.323,Electronic,1.0,0.0

In [90]:
data = df.rename(columns={
    0 : 'Minor',
    1 : 'Major',
})

data.head()

,instance_id,artist_name,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,obtained_date,valence,music_genre,Minor,Major
0,32894,Röyksopp,Röyksopp's Night Out,27.0,0.00468,0.652,-1.0,0.941,0.79200,A#,0.115,-5.201,Minor,0.0748,100.889,4-Apr,0.759,Electronic,0.0,1.0
1,46652,Thievery Corporation,The Shining Path,31.0,0.01270,0.622,218293.0,0.890,0.95000,D,0.124,-7.043,Minor,0.0300,115.00200000000001,4-Apr,0.531,Electronic,0.0,1.0
2,30097,Dillon Francis,Hurricane,28.0,0.00306,0.620,215613.0,0.755,0.01180,G#,0.534,-4.617,Major,0.0345,127.994,4-Apr,0.333,Electronic,1.0,0.0
3,62177,Dubloadz,Nitro,34.0,0.02540,0.774,166875.0,0.700,0.00253,C#,0.157,-4.498,Major,0.2390,128.014,4-Apr,0.270,Electronic,1.0,0.0
4,24907,What So Not,Divide & Conquer,32.0,0.00465,0.638,222369.0,0.587,0.90900,F#,0.157,-6.266,Major,0.0413,145.036,4-Apr,0.323,Electronic,1.0,0.0